title: Travis Appel
description: >-
  Building automation, AI/ML, companion infrastructure,
  creative writing, and working dogs.
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: dark
author:
  name: Travis Appel