title: Travis Appel - Hobbyist, Computer Scientist/Engineer, Writer, AI/ML Enthusiast, and Dog Trainer
description: Building automation, AI [Machine Learning, Simulation, Memory, Companion Infrastructure], Creative Writing, and working dogs
theme: minima
minima:
  skin: dark